# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KrciAi < Formula
  desc "KubeRocketAI CLI - AI-as-Code framework for Your Product Development"
  homepage "https://github.com/KubeRocketCI/kuberocketai"
  version "0.29.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/KubeRocketCI/kuberocketai/releases/download/v0.29.1/krci-ai_Darwin_x86_64.tar.gz"
      sha256 "376c057d0551cbcb3f91f85f1659e7c19e2fe442ba3f77ea8a8abceeb217a195"

      def install
        bin.install "krci-ai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/KubeRocketCI/kuberocketai/releases/download/v0.29.1/krci-ai_Darwin_arm64.tar.gz"
      sha256 "7f63e46230a921672e7797f1bb53748d20c42a9e74002303ef39ca34d7c03c14"

      def install
        bin.install "krci-ai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/KubeRocketCI/kuberocketai/releases/download/v0.29.1/krci-ai_Linux_x86_64.tar.gz"
      sha256 "fe6b834678fb4b7f8a2729dee2d800c55d90e6a035abd89ff57be2394722cf7c"
      def install
        bin.install "krci-ai"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/KubeRocketCI/kuberocketai/releases/download/v0.29.1/krci-ai_Linux_arm64.tar.gz"
      sha256 "a126f4d17a2189c65aa79ed251de3933f9b961073abd949cd8ec2113ae97da9b"
      def install
        bin.install "krci-ai"
      end
    end
  end

  test do
    system "#{bin}/krci-ai", "--version"
    system "#{bin}/krci-ai", "--help"
  end
end
