# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KrciAi < Formula
  desc "KubeRocketAI CLI - AI-as-Code framework for Your Product Development"
  homepage "https://github.com/KubeRocketCI/kuberocketai"
  version "0.12.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/KubeRocketCI/kuberocketai/releases/download/v0.12.0/krci-ai_Darwin_x86_64.tar.gz"
      sha256 "7483d94e72cf974b7c0c8294083eaeb14ccd55449b90065f139fe29810f2157d"

      def install
        bin.install "krci-ai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/KubeRocketCI/kuberocketai/releases/download/v0.12.0/krci-ai_Darwin_arm64.tar.gz"
      sha256 "89d1cb4c8a2d3ccbfcd1f2864ebd3677ae6ed4a92b930aeff7d610adb8f723a5"

      def install
        bin.install "krci-ai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/KubeRocketCI/kuberocketai/releases/download/v0.12.0/krci-ai_Linux_x86_64.tar.gz"
      sha256 "4ccfb6107c039be6ed4d4e81d0094d8c11aa3bca9cd2e94e9807ab61d91e393a"
      def install
        bin.install "krci-ai"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/KubeRocketCI/kuberocketai/releases/download/v0.12.0/krci-ai_Linux_arm64.tar.gz"
      sha256 "5294791718fd1c12d1d624e4f6e96b418960b5c4b7f5ca65400b9345039433f9"
      def install
        bin.install "krci-ai"
      end
    end
  end

  test do
    system "#{bin}/krci-ai", "--version"
    system "#{bin}/krci-ai", "--help"
  end
end
