# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Krci < Formula
  desc "KubeRocketCI CLI - Command-line interface for the KubeRocketCI platform"
  homepage "https://github.com/KubeRocketCI/cli"
  version "0.12.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/KubeRocketCI/cli/releases/download/v0.12.1/krci_Darwin_x86_64.tar.gz"
      sha256 "7ee8924f036e4ad4cebbd7c7fe1f5a1c8da70401e9cd9e3444e2c7236ea149ee"

      define_method(:install) do
        bin.install "krci"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/KubeRocketCI/cli/releases/download/v0.12.1/krci_Darwin_arm64.tar.gz"
      sha256 "3ecf0c86d8dad4508b90201ecd0ae60209be5fbc7e874ab93b544dd9b11817a6"

      define_method(:install) do
        bin.install "krci"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/KubeRocketCI/cli/releases/download/v0.12.1/krci_Linux_x86_64.tar.gz"
      sha256 "3fb0541300142a1ee4b11c0ba5c0a0d7b0dbb8c3c86b0601f72a67e44c753908"
      define_method(:install) do
        bin.install "krci"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KubeRocketCI/cli/releases/download/v0.12.1/krci_Linux_arm64.tar.gz"
      sha256 "9e08cf8cc037f571715132dd42a46cbcc0ba9dcda4db004644f807c66535eeec"
      define_method(:install) do
        bin.install "krci"
      end
    end
  end

  test do
    system "#{bin}/krci", "version"
    system "#{bin}/krci", "--help"
  end
end
